import { v } from "convex/values";

export const storedAttribute = v.object({
  key: v.string(),
  valueJson: v.string(),
});

export const parsedSpanFields = {
  traceId: v.string(),
  spanId: v.string(),
  parentSpanId: v.optional(v.string()),
  name: v.string(),
  kind: v.optional(v.number()),
  startTimeUnixNano: v.optional(v.string()),
  endTimeUnixNano: v.optional(v.string()),
  serviceName: v.optional(v.string()),
  openrouterTraceId: v.optional(v.string()),
  userId: v.optional(v.string()),
  sessionId: v.optional(v.string()),
  requestId: v.optional(v.string()),
  environment: v.optional(v.string()),
  feature: v.optional(v.string()),
  traceName: v.optional(v.string()),
  spanType: v.optional(v.string()),
  entityType: v.optional(v.string()),
  entityId: v.optional(v.string()),
  requestModel: v.optional(v.string()),
  responseModel: v.optional(v.string()),
  generationId: v.optional(v.string()),
  providerName: v.optional(v.string()),
  finishReason: v.optional(v.string()),
  inputTokens: v.optional(v.number()),
  outputTokens: v.optional(v.number()),
  totalTokens: v.optional(v.number()),
  reasoningTokens: v.optional(v.number()),
  cachedInputTokens: v.optional(v.number()),
  inputCost: v.optional(v.number()),
  outputCost: v.optional(v.number()),
  totalCost: v.optional(v.number()),
  openrouterPromptTokens: v.optional(v.number()),
  openrouterCompletionTokens: v.optional(v.number()),
  openrouterUsageCost: v.optional(v.number()),
  upstreamUsageCost: v.optional(v.number()),
  cacheUsageCost: v.optional(v.number()),
  dataUsageCost: v.optional(v.number()),
  webUsageCost: v.optional(v.number()),
  webFetchUsageCost: v.optional(v.number()),
  upstreamWebFetchUsageCost: v.optional(v.number()),
  fileUsageCost: v.optional(v.number()),
  byokInferenceUsageCost: v.optional(v.number()),
  creditPoolUsageCost: v.optional(v.number()),
  creditPoolId: v.optional(v.string()),
  creditPoolExpiresAt: v.optional(v.string()),
  isByok: v.optional(v.boolean()),
  apiKeyName: v.optional(v.string()),
  streamed: v.optional(v.boolean()),
  input: v.optional(v.string()),
  output: v.optional(v.string()),
  attributes: v.array(storedAttribute),
  // Optional only while legacy Prismantix rows are migrated in place.
  resourceAttributes: v.optional(v.array(storedAttribute)),
  eventsJson: v.optional(v.string()),
  linksJson: v.optional(v.string()),
  statusJson: v.optional(v.string()),
} as const;

export const parsedSpan = v.object(parsedSpanFields);
